version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  test:
    docker:
      - image: 'circleci/node:16.13.0-browsers'
    steps:
      - checkout
      - run: npm install && npm run test front-final
  build:
    docker:
      - image: 'circleci/node:16.13.0-browsers'
    steps:
      - checkout
      - run: npm install && npm run build front-final
      - aws-s3/sync:
          from: dist
          to: "s3://ci-cd-fed-sabanafutbol/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"  
workflows:
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
