version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  test:
    docker:
      - image: 'circleci/node:16.13.0-browsers'
    steps:
      - checkout
      - run: npm install && npm run test front-final
  build:
    docker:
      - image: 'circleci/node:16.13.0-browsers'
    steps:
      - checkout
      - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-
      - run: npm install
      - save_cache:
              paths:
                - node_modules
                - ~/.npm
                - ~/.cache
              key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build --prod
      - aws-s3/sync:
          from: build
          to: "s3://ci-cd-fed-sabanafutbol/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"  
workflows:
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
